// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvnbynqxgycqxzmzmftm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2bmJ5bnF4Z3ljcXh6bXptZnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODUwMDUsImV4cCI6MjA3MTE2MTAwNX0.3-hbyCtzAyXraHHNqlBDROgkcgBsf2C6UywrLerqo0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});